version: "3"
services:
  app:
    container_name: express-wm
    restart: always
    build: ./
    volumes:
      - .:/app
    links:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.app-secure.entrypoints=websecure"
      - "traefik.http.routers.app-secure.rule=Host(`worldmanager.victeams.eu`)"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
