version: "3"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    links:
      - mongo
    networks:
      - proxy
      - default
    environment:
       PORT: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.wm-secure.entrypoints=websecure"
      - "traefik.http.routers.wm-secure.rule=Host(`worldmanager.victeams.eu`)"

  mongo:
    container_name: mongo
    image: mongo
    networks:
      - default
    ports:
      - "27017:27017"


networks:
  proxy:
    external: true

